package kpei;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Path;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Tests command-line save-file path resolution for {@link LaunchConfiguration}.
 * This test class was generated by OpenAI Codex.
 */
class LaunchConfigurationTest {

    @TempDir
    Path tempDir;

    @Test
    void getStorageFilePath_firstRunWithRelativePath_pathSaved() throws IOException {
        Path configFile = tempDir.resolve("config.txt");
        LaunchConfiguration launchConfiguration = new LaunchConfiguration(configFile);
        String expectedSaveFilePath = "saves/my_todo_list.txt";

        String actualSaveFilePath = launchConfiguration.getStorageFilePath(new String[]{expectedSaveFilePath});

        assertEquals(expectedSaveFilePath, actualSaveFilePath);
        assertEquals(expectedSaveFilePath, launchConfiguration.getStorageFilePath(new String[]{}));
    }

    @Test
    void getStorageFilePath_newPathSpecified_configuredPathReplaced() throws IOException {
        Path configFile = tempDir.resolve("config.txt");
        LaunchConfiguration launchConfiguration = new LaunchConfiguration(configFile);
        launchConfiguration.getStorageFilePath(new String[]{"saves/old_list.txt"});

        String actualSaveFilePath = launchConfiguration.getStorageFilePath(new String[]{"saves/new_list.txt"});

        assertEquals("saves/new_list.txt", actualSaveFilePath);
        assertEquals("saves/new_list.txt", launchConfiguration.getStorageFilePath(new String[]{}));
    }

    @Test
    void isCli_cliFlagPresent_trueReturned() {
        LaunchConfiguration launchConfiguration = new LaunchConfiguration(tempDir.resolve("config.txt"));

        assertTrue(launchConfiguration.isCli(new String[]{"--cli", "saves/my_todo_list.txt"}));
        assertTrue(launchConfiguration.isCli(new String[]{"saves/my_todo_list.txt", "--cli"}));
        assertFalse(launchConfiguration.isCli(new String[]{"saves/my_todo_list.txt"}));
    }

    @Test
    void getStorageFilePath_multiplePaths_exceptionThrown() {
        LaunchConfiguration launchConfiguration = new LaunchConfiguration(tempDir.resolve("config.txt"));

        assertThrows(IllegalArgumentException.class,
                () -> launchConfiguration.getStorageFilePath(new String[]{"first.txt", "second.txt"}));
    }

    @Test
    void getStorageFilePath_noPathOrConfiguration_exceptionThrown() {
        LaunchConfiguration launchConfiguration = new LaunchConfiguration(tempDir.resolve("config.txt"));

        assertThrows(IllegalArgumentException.class,
                () -> launchConfiguration.getStorageFilePath(new String[]{}));
    }
}
