package kpei.storage;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

import kpei.datatypes.Deadline;
import kpei.datatypes.Event;
import kpei.datatypes.Task;
import kpei.exceptions.BertException;

/**
 * Tests conversion of supported storage records into tasks.
 * This test class was generated by OpenAI Codex.
 */
class StorageParserTest {

    private final StorageParser storageParser = new StorageParser();

    @Test
    void parseStoredTask_validTodoRecord_taskCreated() throws BertException {
        String record = "todo | true | Clean room";

        Task task = storageParser.parseStoredTask(record);

        assertEquals("todo", task.getType());
        assertTrue(task.isMarked());
        assertEquals("Clean room", task.getDescription());
    }

    @Test
    void parseStoredTask_validDeadlineRecord_deadlineCreated() throws BertException {
        String record = "deadline | false | Submit report | 2026-08-29 | 16:00";

        Task task = storageParser.parseStoredTask(record);

        Deadline deadline = assertInstanceOf(Deadline.class, task);
        assertFalse(deadline.isMarked());
        assertEquals("2026-08-29", deadline.getByDate().toString());
        assertEquals("16:00", deadline.getByTime().toString());
    }

    @Test
    void parseStoredTask_validEventRecord_eventCreated() throws BertException {
        String record = "event | 1 | Hackathon | 2026-09-01 | 09:00 | 2026-09-02 | 18:30";

        Task task = storageParser.parseStoredTask(record);

        Event event = assertInstanceOf(Event.class, task);
        assertTrue(event.isMarked());
        assertEquals("2026-09-01", event.getFromDate().toString());
        assertEquals("18:30", event.getToTime().toString());
    }

    @Test
    void parseStoredTask_whitespaceAroundDelimiters_taskCreated() throws BertException {
        String record = "  todo  |  false  |  Clean room  ";

        Task task = storageParser.parseStoredTask(record);

        assertFalse(task.isMarked());
        assertEquals("Clean room", task.getDescription());
    }

    @Test
    void isStoredTask_blankIncompleteAndUnsupportedRecords_falseReturned() {
        assertFalse(storageParser.isStoredTask("   "));
        assertFalse(storageParser.isStoredTask("todo | false"));
        assertFalse(storageParser.isStoredTask("deadline | false | Submit report | 2026-08-29"));
        assertFalse(storageParser.isStoredTask("event | false | Hackathon | 2026-09-01 | 09:00"));
        assertFalse(storageParser.isStoredTask("unknown | false | Unsupported task"));
    }

    @Test
    void parseStoredTask_incompleteOrInvalidRecord_bertExceptionThrown() {
        assertThrows(BertException.class, () -> storageParser.parseStoredTask("todo | false"));
        assertThrows(BertException.class,
                () -> storageParser.parseStoredTask("deadline | false | Submit report | invalid | 16:00"));
    }
}
